'use strict';

// ---------------------------------------------------------------------------
// server/lib/pfep/types.js — PFEP (Plan For Every Part) data contracts.
//
// Shape definitions and validator constants for the PFEP module.
// No runtime logic beyond the exported constant sets.
//
// Naming conventions:
//   PFEPPart       → the atomic unit, one row in pfep_parts
//   PFEPRunSummary → top-level counts for a PFEP CSV import run
//   PFEPAlert      → a cross-reference finding derived from the register
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// VALID_REPLENISHMENT_METHODS
// Mirrors the CHECK constraint on pfep_parts.replenishment_method.
//
//   min_max        — two-bin / min-max replenishment
//   kanban         — card-triggered pull replenishment
//   mrp            — MRP / planning order generated by the ERP
//   consignment    — supplier-owned stock held on-site
//   jit            — just-in-time delivery coordinated with production schedule
//   reorder_point  — fixed reorder point with variable order quantity
//   other          — any method not covered above
// ---------------------------------------------------------------------------
const VALID_REPLENISHMENT_METHODS = new Set([
  'min_max', 'kanban', 'mrp', 'consignment', 'jit', 'reorder_point', 'other',
]);

// ---------------------------------------------------------------------------
// VALID_ABC_CLASSES
// Standard ABC inventory classification.
//   A — high-value / high-movement parts (~20% of SKUs, ~80% of spend)
//   B — medium-value parts
//   C — low-value / low-movement parts
// ---------------------------------------------------------------------------
const VALID_ABC_CLASSES = new Set(['A', 'B', 'C']);

// ---------------------------------------------------------------------------
// VALID_ALERT_TYPES
// Cross-reference alert types emitted by pfepAnalyzer.
//
//   pack_multiple_mismatch   — reorder_point or min_qty is not a multiple of
//                              pack_multiple (would generate partial packs)
//   no_secondary_supplier    — A-class or single-source part with no backup
//   data_gap_supplier        — no supplier recorded (cannot cross-ref POs)
//   data_gap_lead_time       — no lead_time_days (cannot score urgency)
//   data_gap_pack_multiple   — no pack_multiple (cannot validate PO quantities)
//   min_max_inverted         — min_qty >= max_qty (data entry error)
//   reorder_above_max        — reorder_point >= max_qty (will always trigger)
// ---------------------------------------------------------------------------
const VALID_ALERT_TYPES = new Set([
  'pack_multiple_mismatch',
  'no_secondary_supplier',
  'data_gap_supplier',
  'data_gap_lead_time',
  'data_gap_pack_multiple',
  'min_max_inverted',
  'reorder_above_max',
]);

// ===========================================================================
// JSDoc shape definitions (documentation-as-code; no runtime enforcement)
// ===========================================================================

/**
 * @typedef {Object} PFEPPart
 * One normalised part record produced by pfepIngest.
 *
 * @property {string}              part_number           — internal part number (required)
 * @property {string|null}         part_description      — human-readable part name
 * @property {string|null}         commodity_class       — commodity grouping string
 * @property {'A'|'B'|'C'|null}   abc_class             — ABC classification
 * @property {string|null}         supplier              — primary supplier name
 * @property {string|null}         secondary_supplier    — backup / alternate supplier
 * @property {string|null}         supplier_part_number  — supplier's own part code
 * @property {string}              replenishment_method  — one of VALID_REPLENISHMENT_METHODS
 * @property {number|null}         lead_time_days        — standard lead time (calendar days)
 * @property {number|null}         reorder_point         — ROP / safety-stock trigger qty
 * @property {number|null}         min_qty               — minimum replenishment qty
 * @property {number|null}         max_qty               — maximum on-hand target qty
 * @property {number|null}         pack_multiple         — order qty must be a multiple of this
 * @property {number|null}         standard_pack         — supplier's standard pack size
 * @property {string|null}         unit_of_measure       — EA, KG, L, etc.
 * @property {number|null}         unit_cost             — standard cost per unit
 * @property {number|null}         annual_usage          — expected annual demand qty
 * @property {string|null}         point_of_use          — production cell / bin location
 * @property {string|null}         plant                 — facility / site code
 * @property {string|null}         notes                 — free-form notes
 * @property {number}              row_index             — original CSV row order
 */

/**
 * @typedef {Object} PFEPRunSummary
 * Top-level counts for a PFEP CSV import run.
 *
 * @property {number} total_parts           — total rows parsed successfully
 * @property {number} missing_supplier      — parts with no supplier set
 * @property {number} missing_lead_time     — parts with no lead_time_days
 * @property {number} missing_pack_multiple — parts with no pack_multiple
 * @property {number} a_class_count         — count of A-class parts
 * @property {number} b_class_count         — count of B-class parts
 * @property {number} c_class_count         — count of C-class parts
 * @property {number} unclassified_count    — parts with no ABC class
 * @property {number} data_gap_count        — parts with any missing critical field
 * @property {number} alert_count           — total cross-reference alerts generated
 * @property {number} high_alert_count      — High-severity alerts
 */

/**
 * @typedef {Object} PFEPAlert
 * A cross-reference finding produced by pfepAnalyzer.
 *
 * @property {string}  alert_type   — one of VALID_ALERT_TYPES
 * @property {string}  severity     — 'High' | 'Medium' | 'Low'
 * @property {string}  part_number  — the affected part
 * @property {string}  title        — short human-readable title
 * @property {string}  description  — full detail message
 * @property {Object}  context      — arbitrary supplementary data
 */

module.exports = {
  VALID_REPLENISHMENT_METHODS,
  VALID_ABC_CLASSES,
  VALID_ALERT_TYPES,
};
